CREATE DATABASE aufgabe DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE aufgabe;

CREATE TABLE task_entry (
    id VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    taskId VARCHAR(128) NOT NULL,
    inputId VARCHAR(128) NOT NULL,
    updatedAt TIMESTAMP NULL,
    syncedAt TIMESTAMP NULL,
    PRIMARY KEY(id)
);

CREATE TABLE task (
    id VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description TEXT NOT NULL,
    updatedAt TIMESTAMP NULL,
    syncedAt TIMESTAMP NULL,
    bonuslyMessage TEXT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE input (
    id VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ioPin VARCHAR(128) NOT NULL,
    deviceId VARCHAR(128) NOT NULL,
    taskId VARCHAR(128) NOT NULL,
    removedAt TIMESTAMP NULL,
    handler VARCHAR(128) NOT NULL,
    updatedAt TIMESTAMP NULL,
    syncedAt TIMESTAMP NULL,
    PRIMARY KEY(id)
);

CREATE TABLE device (
    id VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NULL,
    description TEXT NULL,
    updatedAt TIMESTAMP NULL,
    syncedAt TIMESTAMP NULL,
    PRIMARY KEY(id)
);

CREATE TABLE output (
    id VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deviceId VARCHAR(128) NOT NULL,
    taskId VARCHAR(128) NOT NULL,
    removedAt TIMESTAMP NULL,
    handler VARCHAR(128) NOT NULL,
    PRIMARY KEY(id)
);